server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1 #tomcat默认2M，超过2M的文件不会被捕获
  port: 8005

# 配置项目信息
spring:
  application:
    profiles:
      active: dev
    name: service-admin
  datasource:
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver          # mysql驱动
    url: jdbc:mysql://localhost:3306/imooc-news-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss

  redis:
    port: 6379
    database: 0
    host: 192.168.8.131

# mybatis配置
mybatis:
  type-aliases-package: com.imooc.pojo
  mapper-locations: classpath:mapper/*.xml
# mybatis mapper配置
# 通用mapper的配置
mapper:
  mappers: com.imooc.my.mapper.MyMapper
  not-empty: false # 在进行数据库操作的时候，判断表达式user != null,是否追加
  identity: MYSQL

# 分页配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true

# 设置域名，在java代码中获取
website:
  domain-name: imoocnews.com